### ISSUE TITLE
[FE] 마이 페이지

### ISSUE THREAD

**Issue by trolliSharkJelly** [trolliSharkJelly/testGit#5]
# Todo
- [x] 마이페이지 마크업(html을 통한 페이지 틀 구현)
- [x] 마이페이지 css(마이페이지 디자인)
- [x] 사용자 정보 GET 함수 구현
- [x] 서버에서 받은 사용자 정보를 이용해 마이페이지에 적용

# End date
9월 10일 오후 2시

**Comment by trolliSharkJelly** [comment]
trolliSharkJelly님, 마이페이지에 로그아웃이나 회원탈퇴 기능을 추가적으로 요청드립니다!
